# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/sharer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15services/sharer.proto\x12\x06sharer\"/\n\rGetKeyRequest\x12\x13\n\x06secret\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_secret\"\x1d\n\x0eGetKeyResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\"?\n\x10GetAccessRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x06secret\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_secret\"#\n\x11GetAccessResponse\x12\x0e\n\x06permit\x18\x01 \x01(\x08\x32\x89\x01\n\x06Hasher\x12=\n\x0cGetUniqueKey\x12\x15.sharer.GetKeyRequest\x1a\x16.sharer.GetKeyResponse\x12@\n\tGetAccess\x12\x18.sharer.GetAccessRequest\x1a\x19.sharer.GetAccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services.sharer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETKEYREQUEST']._serialized_start=33
  _globals['_GETKEYREQUEST']._serialized_end=80
  _globals['_GETKEYRESPONSE']._serialized_start=82
  _globals['_GETKEYRESPONSE']._serialized_end=111
  _globals['_GETACCESSREQUEST']._serialized_start=113
  _globals['_GETACCESSREQUEST']._serialized_end=176
  _globals['_GETACCESSRESPONSE']._serialized_start=178
  _globals['_GETACCESSRESPONSE']._serialized_end=213
  _globals['_HASHER']._serialized_start=216
  _globals['_HASHER']._serialized_end=353
# @@protoc_insertion_point(module_scope)
